### ISSUE TITLE
fab update don't need to use secrets

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/volontulo#784]
we need to omit error:
```
Missing secrets
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/fabric/main.py", line 667, in main
    docstring, callables, default = load_fabfile(fabfile)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/fabric/main.py", line 168, in load_fabfile
    imported = importer(os.path.splitext(fabfile)[0])
  File "/home/travis/build/CodeForPoznan/volontulo/fabfile.py", line 22, in <module>
    from secrets import VOLONTULO_SENTRY_DSN
ImportError: No module named secrets
```

**Comment by magul** [comment]
@rafalkufel
