### ISSUE TITLE
Append slash at the end of password reset API call

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/volontulo#951]
__Description:__

Append slash at the end of password reset API call

__Current behaviour:__

When You try to reset passwor backend raise an error:
```
Internal Server Error: /api/password-reset/MTA1/4w8-89325912be203daaa57a
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 244, in _legacy_get_response
    response = middleware_method(request)
  File "/usr/local/lib/python3.5/dist-packages/django/middleware/common.py", line 63, in process_request
    path = self.get_full_path_with_slash(request)
  File "/usr/local/lib/python3.5/dist-packages/django/middleware/common.py", line 101, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:4200/api/password-reset/MTA1/4w8-89325912be203daaa57a/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
```
__Expected behaviour:__

Password is reseted.

__Steps to reproduce:__

Request reset password and follow link delivered by email.

**Comment by magul** [comment]
Fixed in #954
